import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/Header";
import { GetServerSideProps } from "next";
import HorseCard from "@/components/horseCard/HorseCard";
const inter = Inter({ subsets: ["latin"] });
export interface Horse {
  nom: string;
  race: string;
  sexe: string;
  couleur: string;
  taille: string;
  âge: string;
  description: string;
}
interface Props {
  data: Horse[];
}
export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Equita vente</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {" "}
        <h1>Nos chevaux</h1>
        {data.map((horse) => (
          <HorseCard key={horse.nom} horse={horse} />
        ))}
      </main>
    </>
  );
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await import("../../data/data.json");
  return {
    props: {
      data: data.default,
    },
  };
};
